swagger: "2.0"
host: 0.0.0.0:8070
schemes:
  - http
paths:
    /user/registry/:
        post:
            summary: User registration
            parameters:
                - name: user registration
                in: json
                description:
                required: false
                schema:
                    type: integer
                    format: int32
            responses:
                '200':
                description: An paged array of pets
                headers:
                    x-next:
                        description: A link to the next page of responses
                        schema:
                            type: string
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Pets"
            default:
                description: unexpected error
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Error"